# Generated by Django 3.1.7 on 2021-03-13 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Categoria', '0002_auto_20210313_0934'),
        ('Marca', '0002_auto_20210313_0934'),
        ('Producto', '0002_auto_20210313_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Categoria.categoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Marca.marca'),
            preserve_default=False,
        ),
    ]
